apiVersion: v1
kind: Secret
metadata:
  name: movie-db-secret
type: Opaque
stringData:
  POSTGRES_USER:     movie_db_username
  POSTGRES_PASSWORD: movie_db_password
  POSTGRES_DB:       movie_db_dev
 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movie-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
        - name: postgres
          image: postgres:12.1-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: movie-db-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "movie_db_username"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: movie-db-pvc
 
---
apiVersion: v1
kind: Service
metadata:
  name: movie-db
spec:
  selector:
    app: movie-db
  ports:
    - port: 5432
      targetPort: 5432
 
---
 
apiVersion: v1
kind: Secret
metadata:
  name: cast-db-secret
type: Opaque
stringData:
  POSTGRES_USER:     cast_db_username
  POSTGRES_PASSWORD: cast_db_password
  POSTGRES_DB:       cast_db_dev
 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cast-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
        - name: postgres
          image: postgres:12.1-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: cast-db-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "cast_db_username"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: cast-db-pvc
 
---
apiVersion: v1
kind: Service
metadata:
  name: cast-db
spec:
  selector:
    app: cast-db
  ports:
    - port: 5432
      targetPort: 5432